### ISSUE TITLE
Fail to build on mac + qt 6.2.0

### ISSUE THREAD

**Issue by tibcoplord** [afbjorklund/lima-gui#2]
Trying this out on my mac, I installed qt 6.2.0 ( brew install qt ) and got :

```
$ make
/Library/Developer/CommandLineTools/usr/bin/clang++ -c -pipe -stdlib=libc++ -O2 -std=gnu++1z  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=11 -Wall -Wextra -fPIC -DQT_NO_TERMWIDGET -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -IQSourceHighlite -I/usr/local/lib/QtWidgets.framework/Headers -I/usr/local/lib/QtGui.framework/Headers -I/usr/local/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/usr/local/share/qt/mkspecs/macx-clang -F/usr/local/lib -o main.o main.cpp
In file included from main.cpp:56:
./window.h:74:7: error: definition of type 'QStringList' conflicts with type alias of the same name
class QStringList;
      ^
/usr/local/lib/QtCore.framework/Headers/qcontainerfwd.h:64:7: note: 'QStringList' declared here
using QStringList = QList<QString>;
      ^
main.cpp:62:40: warning: 'AA_UseHighDpiPixmaps' is deprecated: High-DPI pixmaps are always enabled. This attribute no longer has any effect. [-Wdeprecated-declarations]
    QCoreApplication::setAttribute(Qt::AA_UseHighDpiPixmaps);
                                       ^
/usr/local/lib/QtCore.framework/Headers/qnamespace.h:462:30: note: 'AA_UseHighDpiPixmaps' has been explicitly marked deprecated here
        AA_UseHighDpiPixmaps Q_DECL_ENUMERATOR_DEPRECATED_X(
                             ^
/usr/local/lib/QtCore.framework/Headers/qcompilerdetection.h:1151:45: note: expanded from macro 'Q_DECL_ENUMERATOR_DEPRECATED_X'
#  define Q_DECL_ENUMERATOR_DEPRECATED_X(x) Q_DECL_DEPRECATED_X(x)
                                            ^
/usr/local/lib/QtCore.framework/Headers/qcompilerdetection.h:1146:36: note: expanded from macro 'Q_DECL_DEPRECATED_X'
#  define Q_DECL_DEPRECATED_X(x) [[deprecated(x)]]
                                   ^
1 warning and 1 error generated.
make: *** [main.o] Error 1
```
